// generated by dbgen ; DO NOT EDIT

package main

import (
	"time"
)

//
// user DBObject generator
//
func (o user) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// user DBObject interface functions
//
func (o *user) InsertValues() []interface{} {
	return []interface{}{o.Login, o.First, o.Last, o.Email, o.APIKey, o.Level}
}

func (o *user) UpdateValues() []interface{} {
	return []interface{}{o.Login, o.First, o.Last, o.Email, o.APIKey, o.Level, o.USR}
}

func (o *user) MemberPointers() []interface{} {
	return []interface{}{&o.USR, &o.Login, &o.First, &o.Last, &o.Email, &o.APIKey, &o.Level}
}

func (o *user) Key() int64 {
	return o.USR
}

func (o *user) SetID(id int64) {
	o.USR = id
}

func (o *user) TableName() string {
	return "users"
}

func (o *user) SelectFields() string {
	return "usr,login,firstname,lastname,email,apikey,admin"
}

func (o *user) InsertFields() string {
	return "usr,login,firstname,lastname,email,apikey,admin"
}

func (o *user) KeyField() string {
	return "usr"
}

func (o *user) KeyName() string {
	return "USR"
}

func (o *user) Names() []string {
	return []string{"Login", "First", "Last", "Email", "APIKey", "Level"}
}

func (o *user) ModifiedBy(user int64, t time.Time) {
}

//
// fullUser DBObject generator
//
func (o fullUser) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// fullUser DBObject interface functions
//
func (o *fullUser) InsertValues() []interface{} {
	return []interface{}{o.APIKey, o.Password, o.Salt, o.Level, o.Login, o.First, o.Last, o.Email}
}

func (o *fullUser) UpdateValues() []interface{} {
	return []interface{}{o.APIKey, o.Password, o.Salt, o.Level, o.Login, o.First, o.Last, o.Email, o.USR}
}

func (o *fullUser) MemberPointers() []interface{} {
	return []interface{}{&o.USR, &o.APIKey, &o.Password, &o.Salt, &o.Level, &o.Login, &o.First, &o.Last, &o.Email}
}

func (o *fullUser) Key() int64 {
	return o.USR
}

func (o *fullUser) SetID(id int64) {
	o.USR = id
}

func (o *fullUser) TableName() string {
	return "users"
}

func (o *fullUser) SelectFields() string {
	return "usr,apikey,pw_hash,pw_salt,admin,login,firstname,lastname,email"
}

func (o *fullUser) InsertFields() string {
	return "usr,apikey,pw_hash,pw_salt,admin,login,firstname,lastname,email"
}

func (o *fullUser) KeyField() string {
	return "usr"
}

func (o *fullUser) KeyName() string {
	return "USR"
}

func (o *fullUser) Names() []string {
	return []string{"APIKey", "Password", "Salt", "Level", "Login", "First", "Last", "Email"}
}

func (o *fullUser) ModifiedBy(user int64, t time.Time) {
}

//
// site DBObject generator
//
func (o site) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// site DBObject interface functions
//
func (o *site) InsertValues() []interface{} {
	return []interface{}{o.City, o.State, o.Country, o.Phone, o.Web, o.USR, o.Modified, o.Name, o.Address, o.Postal}
}

func (o *site) UpdateValues() []interface{} {
	return []interface{}{o.City, o.State, o.Country, o.Phone, o.Web, o.USR, o.Modified, o.Name, o.Address, o.Postal, o.STI}
}

func (o *site) MemberPointers() []interface{} {
	return []interface{}{&o.STI, &o.City, &o.State, &o.Country, &o.Phone, &o.Web, &o.USR, &o.Modified, &o.Name, &o.Address, &o.Postal}
}

func (o *site) Key() int64 {
	return o.STI
}

func (o *site) SetID(id int64) {
	o.STI = id
}

func (o *site) TableName() string {
	return "sites"
}

func (o *site) SelectFields() string {
	return "sti,city,state,country,phone,web,usr,ts,name,address,postal"
}

func (o *site) InsertFields() string {
	return "sti,city,state,country,phone,web,usr,ts,name,address,postal"
}

func (o *site) KeyField() string {
	return "sti"
}

func (o *site) KeyName() string {
	return "STI"
}

func (o *site) Names() []string {
	return []string{"City", "State", "Country", "Phone", "Web", "USR", "Modified", "Name", "Address", "Postal"}
}

func (o *site) ModifiedBy(user int64, t time.Time) {
	o.USR = &user
	o.Modified = t
}

//
// pxeDevice DBObject generator
//
func (o pxeDevice) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// pxeDevice DBObject interface functions
//
func (o *pxeDevice) InsertValues() []interface{} {
	return []interface{}{o.STI, o.RU, o.Hostname, o.Profile, o.IPMI, o.RID, o.Site, o.Rack, o.MAC, o.IP, o.Note}
}

func (o *pxeDevice) UpdateValues() []interface{} {
	return []interface{}{o.STI, o.RU, o.Hostname, o.Profile, o.IPMI, o.RID, o.Site, o.Rack, o.MAC, o.IP, o.Note, o.DID}
}

func (o *pxeDevice) MemberPointers() []interface{} {
	return []interface{}{&o.DID, &o.STI, &o.RU, &o.Hostname, &o.Profile, &o.IPMI, &o.RID, &o.Site, &o.Rack, &o.MAC, &o.IP, &o.Note}
}

func (o *pxeDevice) Key() int64 {
	return o.DID
}

func (o *pxeDevice) SetID(id int64) {
	o.DID = id
}

func (o *pxeDevice) TableName() string {
	return "pxedevice"
}

func (o *pxeDevice) SelectFields() string {
	return "did,sti,ru,hostname,profile,ipmi,rid,site,rack,mac,ip,note"
}

func (o *pxeDevice) InsertFields() string {
	return "did,sti,ru,hostname,profile,ipmi,rid,site,rack,mac,ip,note"
}

func (o *pxeDevice) KeyField() string {
	return "did"
}

func (o *pxeDevice) KeyName() string {
	return "DID"
}

func (o *pxeDevice) Names() []string {
	return []string{"STI", "RU", "Hostname", "Profile", "IPMI", "RID", "Site", "Rack", "MAC", "IP", "Note"}
}

func (o *pxeDevice) ModifiedBy(user int64, t time.Time) {
}

//
// audit DBObject generator
//
func (o audit) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// audit DBObject interface functions
//
func (o *audit) InsertValues() []interface{} {
	return []interface{}{o.Log, o.User, o.TS, o.USR, o.STI, o.Site, o.Hostname}
}

func (o *audit) UpdateValues() []interface{} {
	return []interface{}{o.Log, o.User, o.TS, o.USR, o.STI, o.Site, o.Hostname, o.AID}
}

func (o *audit) MemberPointers() []interface{} {
	return []interface{}{&o.AID, &o.Log, &o.User, &o.TS, &o.USR, &o.STI, &o.Site, &o.Hostname}
}

func (o *audit) Key() int64 {
	return o.AID
}

func (o *audit) SetID(id int64) {
	o.AID = id
}

func (o *audit) TableName() string {
	return "audit_view"
}

func (o *audit) SelectFields() string {
	return "aid,log,user,ts,usr,sti,site,hostname"
}

func (o *audit) InsertFields() string {
	return "aid,log,user,ts,usr,sti,site,hostname"
}

func (o *audit) KeyField() string {
	return "aid"
}

func (o *audit) KeyName() string {
	return "AID"
}

func (o *audit) Names() []string {
	return []string{"Log", "User", "TS", "USR", "STI", "Site", "Hostname"}
}

func (o *audit) ModifiedBy(user int64, t time.Time) {
	o.TS = t
}

//
// pxeHost DBObject generator
//
func (o pxeHost) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// pxeHost DBObject interface functions
//
func (o *pxeHost) InsertValues() []interface{} {
	return []interface{}{o.Sitename, o.Hostname}
}

func (o *pxeHost) UpdateValues() []interface{} {
	return []interface{}{o.Sitename, o.Hostname, o.ID}
}

func (o *pxeHost) MemberPointers() []interface{} {
	return []interface{}{&o.ID, &o.Sitename, &o.Hostname}
}

func (o *pxeHost) Key() int64 {
	return o.ID
}

func (o *pxeHost) SetID(id int64) {
	o.ID = id
}

func (o *pxeHost) TableName() string {
	return "pxehosts"
}

func (o *pxeHost) SelectFields() string {
	return "id,sitename,hostname"
}

func (o *pxeHost) InsertFields() string {
	return "id,sitename,hostname"
}

func (o *pxeHost) KeyField() string {
	return "id"
}

func (o *pxeHost) KeyName() string {
	return "ID"
}

func (o *pxeHost) Names() []string {
	return []string{"Sitename", "Hostname"}
}

func (o *pxeHost) ModifiedBy(user int64, t time.Time) {
}

//
// event DBObject generator
//
func (o event) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// event DBObject interface functions
//
func (o *event) InsertValues() []interface{} {
	return []interface{}{o.TS, o.Host, o.Kind, o.Msg}
}

func (o *event) UpdateValues() []interface{} {
	return []interface{}{o.TS, o.Host, o.Kind, o.Msg}
}

func (o *event) MemberPointers() []interface{} {
	return []interface{}{&o.TS, &o.Host, &o.Kind, &o.Msg}
}

func (o *event) Key() int64 {
	return 0
}

func (o *event) SetID(id int64) {
}

func (o *event) TableName() string {
	return "events"
}

func (o *event) SelectFields() string {
	return "ts,host,kind,msg"
}

func (o *event) InsertFields() string {
	return "ts,host,kind,msg"
}

func (o *event) KeyField() string {
	return ""
}

func (o *event) KeyName() string {
	return ""
}

func (o *event) Names() []string {
	return []string{"TS", "Host", "Kind", "Msg"}
}

func (o *event) ModifiedBy(user int64, t time.Time) {
}
