// generated by dbgen ; DO NOT EDIT

package main

import (
	"time"
)

//
// user DBObject generator
//
func (o user) NewObj() interface{} {
	return new(user)
}

//
// user DBObject interface functions
//
func (o *user) InsertValues() []interface{} {
	return []interface{}{o.Level, o.Login, o.First, o.Last, o.Email, o.APIKey}
}

func (o *user) UpdateValues() []interface{} {
	return []interface{}{o.Level, o.Login, o.First, o.Last, o.Email, o.APIKey, o.USR}
}

func (o *user) MemberPointers() []interface{} {
	return []interface{}{&o.USR, &o.Level, &o.Login, &o.First, &o.Last, &o.Email, &o.APIKey}
}

func (o *user) Key() int64 {
	return o.USR
}

func (o *user) SetID(id int64) {
	o.USR = id
}

func (o *user) TableName() string {
	return "users"
}

func (o *user) SelectFields() string {
	return "usr,admin,login,firstname,lastname,email,apikey"
}

func (o *user) InsertFields() string {
	return "usr,admin,login,firstname,lastname,email,apikey"
}

func (o *user) KeyField() string {
	return "usr"
}

func (o *user) KeyName() string {
	return "USR"
}

func (o *user) Names() []string {
	return []string{"Level", "Login", "First", "Last", "Email", "APIKey"}
}

func (o *user) ModifiedBy(user int64, t time.Time) {
}

//
// fullUser DBObject generator
//
func (o fullUser) NewObj() interface{} {
	return new(fullUser)
}

//
// fullUser DBObject interface functions
//
func (o *fullUser) InsertValues() []interface{} {
	return []interface{}{o.Last, o.Email, o.APIKey, o.Password, o.Salt, o.Level, o.Login, o.First}
}

func (o *fullUser) UpdateValues() []interface{} {
	return []interface{}{o.Last, o.Email, o.APIKey, o.Password, o.Salt, o.Level, o.Login, o.First, o.USR}
}

func (o *fullUser) MemberPointers() []interface{} {
	return []interface{}{&o.USR, &o.Last, &o.Email, &o.APIKey, &o.Password, &o.Salt, &o.Level, &o.Login, &o.First}
}

func (o *fullUser) Key() int64 {
	return o.USR
}

func (o *fullUser) SetID(id int64) {
	o.USR = id
}

func (o *fullUser) TableName() string {
	return "users"
}

func (o *fullUser) SelectFields() string {
	return "usr,lastname,email,apikey,pw_hash,pw_salt,admin,login,firstname"
}

func (o *fullUser) InsertFields() string {
	return "usr,lastname,email,apikey,pw_hash,pw_salt,admin,login,firstname"
}

func (o *fullUser) KeyField() string {
	return "usr"
}

func (o *fullUser) KeyName() string {
	return "USR"
}

func (o *fullUser) Names() []string {
	return []string{"Last", "Email", "APIKey", "Password", "Salt", "Level", "Login", "First"}
}

func (o *fullUser) ModifiedBy(user int64, t time.Time) {
}

//
// site DBObject generator
//
func (o site) NewObj() interface{} {
	return new(site)
}

//
// site DBObject interface functions
//
func (o *site) InsertValues() []interface{} {
	return []interface{}{o.Country, o.Web, o.USR, o.Address, o.State, o.Postal, o.Phone, o.Modified, o.Name, o.City}
}

func (o *site) UpdateValues() []interface{} {
	return []interface{}{o.Country, o.Web, o.USR, o.Address, o.State, o.Postal, o.Phone, o.Modified, o.Name, o.City, o.STI}
}

func (o *site) MemberPointers() []interface{} {
	return []interface{}{&o.STI, &o.Country, &o.Web, &o.USR, &o.Address, &o.State, &o.Postal, &o.Phone, &o.Modified, &o.Name, &o.City}
}

func (o *site) Key() int64 {
	return o.STI
}

func (o *site) SetID(id int64) {
	o.STI = id
}

func (o *site) TableName() string {
	return "sites"
}

func (o *site) SelectFields() string {
	return "sti,country,web,usr,address,state,postal,phone,ts,name,city"
}

func (o *site) InsertFields() string {
	return "sti,country,web,usr,address,state,postal,phone,ts,name,city"
}

func (o *site) KeyField() string {
	return "sti"
}

func (o *site) KeyName() string {
	return "STI"
}

func (o *site) Names() []string {
	return []string{"Country", "Web", "USR", "Address", "State", "Postal", "Phone", "Modified", "Name", "City"}
}

func (o *site) ModifiedBy(user int64, t time.Time) {
	o.USR = &user
	o.Modified = t
}

//
// pxeDevice DBObject generator
//
func (o pxeDevice) NewObj() interface{} {
	return new(pxeDevice)
}

//
// pxeDevice DBObject interface functions
//
func (o *pxeDevice) InsertValues() []interface{} {
	return []interface{}{o.Hostname, o.MAC, o.IPMI, o.STI, o.Site, o.RU, o.IP, o.Note, o.RID, o.Rack, o.Profile}
}

func (o *pxeDevice) UpdateValues() []interface{} {
	return []interface{}{o.Hostname, o.MAC, o.IPMI, o.STI, o.Site, o.RU, o.IP, o.Note, o.RID, o.Rack, o.Profile, o.DID}
}

func (o *pxeDevice) MemberPointers() []interface{} {
	return []interface{}{&o.DID, &o.Hostname, &o.MAC, &o.IPMI, &o.STI, &o.Site, &o.RU, &o.IP, &o.Note, &o.RID, &o.Rack, &o.Profile}
}

func (o *pxeDevice) Key() int64 {
	return o.DID
}

func (o *pxeDevice) SetID(id int64) {
	o.DID = id
}

func (o *pxeDevice) TableName() string {
	return "pxedevice"
}

func (o *pxeDevice) SelectFields() string {
	return "did,hostname,mac,ipmi,sti,site,ru,ip,note,rid,rack,profile"
}

func (o *pxeDevice) InsertFields() string {
	return "did,hostname,mac,ipmi,sti,site,ru,ip,note,rid,rack,profile"
}

func (o *pxeDevice) KeyField() string {
	return "did"
}

func (o *pxeDevice) KeyName() string {
	return "DID"
}

func (o *pxeDevice) Names() []string {
	return []string{"Hostname", "MAC", "IPMI", "STI", "Site", "RU", "IP", "Note", "RID", "Rack", "Profile"}
}

func (o *pxeDevice) ModifiedBy(user int64, t time.Time) {
}

//
// audit DBObject generator
//
func (o audit) NewObj() interface{} {
	return new(audit)
}

//
// audit DBObject interface functions
//
func (o *audit) InsertValues() []interface{} {
	return []interface{}{o.STI, o.Site, o.Hostname, o.Log, o.User, o.TS, o.USR}
}

func (o *audit) UpdateValues() []interface{} {
	return []interface{}{o.STI, o.Site, o.Hostname, o.Log, o.User, o.TS, o.USR, o.AID}
}

func (o *audit) MemberPointers() []interface{} {
	return []interface{}{&o.AID, &o.STI, &o.Site, &o.Hostname, &o.Log, &o.User, &o.TS, &o.USR}
}

func (o *audit) Key() int64 {
	return o.AID
}

func (o *audit) SetID(id int64) {
	o.AID = id
}

func (o *audit) TableName() string {
	return "audit_view"
}

func (o *audit) SelectFields() string {
	return "aid,sti,site,hostname,log,user,ts,usr"
}

func (o *audit) InsertFields() string {
	return "aid,sti,site,hostname,log,user,ts,usr"
}

func (o *audit) KeyField() string {
	return "aid"
}

func (o *audit) KeyName() string {
	return "AID"
}

func (o *audit) Names() []string {
	return []string{"STI", "Site", "Hostname", "Log", "User", "TS", "USR"}
}

func (o *audit) ModifiedBy(user int64, t time.Time) {
	o.TS = t
}

//
// pxeHost DBObject generator
//
func (o pxeHost) NewObj() interface{} {
	return new(pxeHost)
}

//
// pxeHost DBObject interface functions
//
func (o *pxeHost) InsertValues() []interface{} {
	return []interface{}{o.Sitename, o.Hostname}
}

func (o *pxeHost) UpdateValues() []interface{} {
	return []interface{}{o.Sitename, o.Hostname}
}

func (o *pxeHost) MemberPointers() []interface{} {
	return []interface{}{&o.Sitename, &o.Hostname}
}

func (o *pxeHost) Key() int64 {
	return 0
}

func (o *pxeHost) SetID(id int64) {
}

func (o *pxeHost) TableName() string {
	return "pxehosts"
}

func (o *pxeHost) SelectFields() string {
	return "sitename,hostname"
}

func (o *pxeHost) InsertFields() string {
	return "sitename,hostname"
}

func (o *pxeHost) KeyField() string {
	return ""
}

func (o *pxeHost) KeyName() string {
	return ""
}

func (o *pxeHost) Names() []string {
	return []string{"Sitename", "Hostname"}
}

func (o *pxeHost) ModifiedBy(user int64, t time.Time) {
}
