#!/bin/bash

[[ -f /etc/sysconfig/imgman ]] && . /etc/sysconfig/imgman

IMGHOST=${IMGHOST:-127.0.0.1}
IMGPORT=${IMGPORT:-9999}
IMGMAC=$(ethtool -P eth0 | awk '{print $3}')

case $1 in
        start) MSG=BOOT ;; 
        stop)  MSG=SHUTDOWN ;;
        *) echo >&2 "invalid command: $1"; exit 1 ;;
esac

echo "- - $MSG $IMGMAC" > /dev/udp/$IMGHOST/$IMGPORT

