#!/bin/sh

# the following is the LSB init header see
# http://www.linux-foundation.org/spec//booksets/LSB-Core-generic/LSB-Core-generic.html#INITSCRCOMCONV
#
### BEGIN INIT INFO
# Provides: pxestats
# Required-Start: $network messagebus
# Required-Stop: $network messagebus
# Default-Start: 3 4 5
# Short-Description: daemon for to capture network device statistics
# Description: management system
#               A web-based system for managing servers in multiple datacenters
#               Server inventory 
### END INIT INFO

# the following is chkconfig init header
#
# pxestats:   datacenter manager
#
# chkconfig: 345 99 03
# description:  This datacenter manangement system\
#               See https://github.com/paulstuart/pxestats
#
# processname: pxestats
# pidfile: /var/run/pxestats.pid
#

# Source function library.
. /etc/rc.d/init.d/functions

SERVICE=pxestats
PROCESS=pxestats
PID_DIR=/var/run
LOG_DIR=/var/log
LOCK_DIR=/var/lock/subsys
PIDFILE=$PID_DIR/$SERVICE.pid

INITCTL_PATH=/sbin/initctl

# customize as needed
CUSTOM_CONFIG=${CUSTOM_CONFIG:-/etc/sysconfig/pxestats}
test -f $CUSTOM_CONFIG && . $CUSTOM_CONFIG 


fail() {
    echo -n "$*"
    echo_failure 
    echo
    exit 1
}

start() {
    echo -n $"Starting $SERVICE daemon: "

    # make sure it's available in path and permissions are ok
    which $PROCESS > /dev/null 2>&1 || fail "missing $PROCESS command" 
    [ -w $PID_DIR ]  || fail "no write access in $PID_DIR"
    [ -w $LOG_DIR ]  || fail "no write access in $LOG_DIR"
    [ -w $LOCK_DIR ] || fail "no write access in $LOCK_DIR"

    # fire it up!
    __pids_var_run $PROCESS
    [ $? -eq 0 ] && echo_failure && exit $?
    nohup $PROCESS >> $LOG_DIR/$SERVICE.log 2>&1 &
    RETVAL=$?
    PID=$!

    if [ $RETVAL -eq 0 ]; then
        echo $PID > $PIDFILE 
        echo_success 
        touch $LOCK_DIR/$SERVICE
    else
        echo_failure
    fi
    echo
}

stop() {
    echo -n $"Stopping $SERVICE daemon: "

    killproc -p $PIDFILE $PROCESS
    RETVAL=$?
    echo
    if [ $RETVAL -eq 0 ]; then
        rm -f /var/lock/subsys/$SERVICE
    else
        exit $RETVAL
    fi
}

restart() {
    stop
    start
}

reload() {
    echo -n $"Reloading $SERVICE configuration: "
    initctl_check

    killproc -p $PIDFILE $PROCESS -HUP
    RETVAL=$?
    echo
    return $RETVAL
}

# See how we were called.
case "$1" in
    start|stop|restart|reload)
        $1
        ;;
    status)
        status -p $PIDFILE $PROCESS
        RETVAL=$?
        ;;
    force-reload)
        reload
        ;;
    condrestart|try-restart)
        [ -f /var/lock/subsys/$SERVICE ] && restart || :
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|reload|force-reload|try-restart}"
        exit 2
        ;;
esac
exit $RETVAL
